version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ideas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - internal

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "dbname=ideas_db user=postgres password=postgres host=db"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - internal

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    networks:
      - internal
      - public

volumes:
  postgres-data:

networks:
  internal:
    internal: true
  public:
    external: false

