# AWS External Secret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-aws
  namespace: proj-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "dbadmin"
        password: "{{ .password | toString }}"
        database: "appdb"
        host: "{{ .Values.database.endpoint }}"
  data:
  - secretKey: password
    remoteRef:
      key: /proj/dev/database/password

---
# GCP External Secret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-gcp
  namespace: proj-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "dbadmin"
        password: "{{ .password | toString }}"
        database: "appdb"
        host: "{{ .Values.database.endpoint }}"
  data:
  - secretKey: password
    remoteRef:
      key: proj-dev-db-password

---
# Azure External Secret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-azure
  namespace: proj-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "dbadmin"
        password: "{{ .password | toString }}"
        database: "appdb"
        host: "{{ .Values.database.endpoint }}"
  data:
  - secretKey: password
    remoteRef:
      key: database-password
