# AWS SecretStore Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameter-store
  namespace: proj-app
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        # Use IRSA (IAM Roles for Service Accounts) or instance profile
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
# GCP SecretStore Configuration  
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: proj-app
spec:
  provider:
    gcpsm:
      projectId: "{{ .Values.gcp.projectId }}"
      auth:
        workloadIdentity:
          clusterLocation: "{{ .Values.gcp.region }}"
          clusterName: "{{ .Values.gcp.clusterName }}"
          serviceAccountRef:
            name: external-secrets-sa

---
# Azure Key Vault SecretStore Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: proj-app
spec:
  provider:
    azurekv:
      vaultUrl: "https://proj-dev-kv.vault.azure.net/"
      auth:
        managedIdentity:
          clientId: "{{ .Values.azure.clientId }}"
