apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: proj-app
  labels:
    app: database
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64)
  password: cGFzc3dvcmQ=  # password (base64)
  database: cHJvamRi     # projdb (base64)
