apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: proj-app
  labels:
    app: database
spec:
  type: ExternalName
  externalName: proj-dev-db.cuzwa0qw6qdo.us-east-1.rds.amazonaws.com
