apiVersion: batch/v1
kind: Job
metadata:
  name: database-init
  namespace: proj-app
spec:
  template:
    spec:
      containers:
      - name: postgres-client
        image: postgres:15
        command: ["/bin/bash"]
        args:
          - -c
          - |
            psql $DATABASE_URL << 'EOF'
            CREATE TABLE IF NOT EXISTS ideas (
                id SERIAL PRIMARY KEY,
                content TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW()
            );
            
            -- Add some sample data
            INSERT INTO ideas (content, created_at) VALUES 
            ('Implement a user authentication system', NOW()),
            ('Add a search feature for ideas', NOW()),
            ('Create a mobile application', NOW()),
            ('Integrate with third-party services', NOW())
            ON CONFLICT DO NOTHING;
            
            -- Verify the table was created
            SELECT COUNT(*) FROM ideas;
            EOF
        env:
        - name: DB_HOST
          value: "database-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials-fallback
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials-fallback
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials-fallback
              key: database
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)"
      restartPolicy: Never
  backoffLimit: 4
